### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Zwork101** [repl-it-discord/HootHoot#1]
Here's some things that need to be implemented as of the initial commit.

 - [x] ModMail type system
 - [x] Complete logging (for discord)
 - [ ] Complete logging (for bot)
 - [ ] Repl Talk flagging for helpers
 - [ ] Organize bugs / feedback?
 - [ ] Block messages with spam / zargo / etc

If you have a suggestion, please suggest it in the comments. If you'd like to contribute, thanks! Just make a PR an mention what you're adding on the roadmap. Do not add features not on the roadmap, they will be declined.

**Comment by A5rocks** [comment]
Suggestion for the "organize bugs / feedback" thing: make a `bug` or `feedback` command that posts the contents onto https://repl.it/feedback or https://repl.it/bugs (as long as you can do that without a captcha)

**Comment by Zwork101** [comment]
I'm definitely tempted too, I think I'll talk with a repl.it admin about that first though.

**Comment by Aiden-Oomen** [comment]
I think itd be a good idea to get a modmail ban feature. I looked through all of this and didnt see an instance of it.
